# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'events.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(690, 590)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 653, 818))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_2 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_39 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_2.addWidget(self.label_39, 37, 1, 1, 1)
        self.label_33 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_2.addWidget(self.label_33, 29, 2, 1, 1)
        self.label_17 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_2.addWidget(self.label_17, 2, 1, 1, 1)
        self.label_71 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.gridLayout_2.addWidget(self.label_71, 35, 1, 1, 1)
        self.label_46 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout_2.addWidget(self.label_46, 38, 2, 1, 1)
        self.label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 1, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_2.addWidget(self.label_18, 3, 1, 1, 1)
        self.label_76 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.gridLayout_2.addWidget(self.label_76, 16, 0, 1, 1)
        self.label_75 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.gridLayout_2.addWidget(self.label_75, 15, 0, 1, 1)
        self.label_26 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_2.addWidget(self.label_26, 32, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 19, 1, 1, 1)
        self.label_66 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.gridLayout_2.addWidget(self.label_66, 31, 1, 1, 1)
        self.label_59 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.gridLayout_2.addWidget(self.label_59, 22, 0, 1, 1)
        self.label_54 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.gridLayout_2.addWidget(self.label_54, 23, 0, 1, 1)
        self.label_32 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_2.addWidget(self.label_32, 27, 0, 1, 1)
        self.label_56 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.gridLayout_2.addWidget(self.label_56, 25, 0, 1, 1)
        self.label_58 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.gridLayout_2.addWidget(self.label_58, 26, 0, 1, 1)
        self.label_48 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.gridLayout_2.addWidget(self.label_48, 32, 1, 1, 1)
        self.label_51 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.gridLayout_2.addWidget(self.label_51, 24, 0, 1, 1)
        self.label_55 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.gridLayout_2.addWidget(self.label_55, 25, 2, 1, 1)
        self.label_15 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_2.addWidget(self.label_15, 7, 0, 1, 1)
        self.label_69 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.gridLayout_2.addWidget(self.label_69, 30, 0, 1, 1)
        self.label_42 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_2.addWidget(self.label_42, 10, 0, 1, 1)
        self.label_53 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.gridLayout_2.addWidget(self.label_53, 24, 2, 1, 1)
        self.label_30 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_2.addWidget(self.label_30, 28, 0, 1, 1)
        self.label_37 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_2.addWidget(self.label_37, 29, 0, 1, 1)
        self.label_57 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.gridLayout_2.addWidget(self.label_57, 23, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 34, 0, 1, 1)
        self.label_31 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_2.addWidget(self.label_31, 11, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_20 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_2.addWidget(self.label_20, 5, 1, 1, 1)
        self.label_47 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.gridLayout_2.addWidget(self.label_47, 12, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_2.addWidget(self.label_16, 8, 0, 1, 1)
        self.label_25 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_2.addWidget(self.label_25, 13, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 3, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 4, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 6, 0, 1, 1)
        self.label_23 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_2.addWidget(self.label_23, 9, 0, 1, 1)
        self.label_73 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.gridLayout_2.addWidget(self.label_73, 14, 0, 1, 1)
        self.label_77 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_77.setObjectName(_fromUtf8("label_77"))
        self.gridLayout_2.addWidget(self.label_77, 18, 0, 1, 1)
        self.label_78 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_78.setObjectName(_fromUtf8("label_78"))
        self.gridLayout_2.addWidget(self.label_78, 17, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 5, 0, 1, 1)
        self.label_24 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_2.addWidget(self.label_24, 28, 2, 1, 1)
        self.label_44 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_2.addWidget(self.label_44, 36, 2, 1, 1)
        self.label_36 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_2.addWidget(self.label_36, 33, 0, 1, 1)
        self.label_67 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.gridLayout_2.addWidget(self.label_67, 31, 2, 1, 1)
        self.label_45 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_2.addWidget(self.label_45, 37, 2, 1, 1)
        self.label_64 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.gridLayout_2.addWidget(self.label_64, 30, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 19, 0, 1, 1)
        self.label_72 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.gridLayout_2.addWidget(self.label_72, 35, 2, 1, 1)
        self.label_41 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_2.addWidget(self.label_41, 38, 0, 1, 1)
        self.label_22 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_2.addWidget(self.label_22, 7, 1, 1, 1)
        self.label_79 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_79.setObjectName(_fromUtf8("label_79"))
        self.gridLayout_2.addWidget(self.label_79, 8, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_2.addWidget(self.label_19, 4, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_2.addWidget(self.label_21, 6, 1, 1, 1)
        self.label_43 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_2.addWidget(self.label_43, 32, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 20, 0, 1, 1)
        self.label_34 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_2.addWidget(self.label_34, 28, 1, 1, 1)
        self.label_62 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.gridLayout_2.addWidget(self.label_62, 26, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 19, 2, 1, 1)
        self.label_60 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_60.setText(_fromUtf8(""))
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.gridLayout_2.addWidget(self.label_60, 22, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 21, 0, 1, 1)
        self.label_52 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.gridLayout_2.addWidget(self.label_52, 24, 1, 1, 1)
        self.label_50 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_50.setText(_fromUtf8(""))
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.gridLayout_2.addWidget(self.label_50, 22, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 20, 2, 1, 1)
        self.label_27 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_27.setText(_fromUtf8(""))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_2.addWidget(self.label_27, 29, 1, 1, 1)
        self.label_65 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.gridLayout_2.addWidget(self.label_65, 30, 1, 1, 1)
        self.label_63 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.gridLayout_2.addWidget(self.label_63, 25, 1, 1, 1)
        self.label_70 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.gridLayout_2.addWidget(self.label_70, 35, 0, 1, 1)
        self.label_61 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.gridLayout_2.addWidget(self.label_61, 26, 2, 1, 1)
        self.label_28 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_2.addWidget(self.label_28, 36, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 20, 1, 1, 1)
        self.label_38 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_2.addWidget(self.label_38, 37, 0, 1, 1)
        self.label_29 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_2.addWidget(self.label_29, 27, 1, 1, 1)
        self.label_40 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_2.addWidget(self.label_40, 38, 1, 1, 1)
        self.label_35 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_2.addWidget(self.label_35, 27, 2, 1, 1)
        self.label_49 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.gridLayout_2.addWidget(self.label_49, 23, 1, 1, 1)
        self.label_74 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.gridLayout_2.addWidget(self.label_74, 36, 1, 1, 1)
        self.label_68 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.gridLayout_2.addWidget(self.label_68, 31, 0, 1, 1)
        self.label_80 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_80.setObjectName(_fromUtf8("label_80"))
        self.gridLayout_2.addWidget(self.label_80, 10, 1, 1, 1)
        self.label_81 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_81.setObjectName(_fromUtf8("label_81"))
        self.gridLayout_2.addWidget(self.label_81, 11, 1, 1, 1)
        self.label_82 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_82.setObjectName(_fromUtf8("label_82"))
        self.gridLayout_2.addWidget(self.label_82, 12, 1, 1, 1)
        self.label_83 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_83.setObjectName(_fromUtf8("label_83"))
        self.gridLayout_2.addWidget(self.label_83, 14, 1, 1, 1)
        self.label_84 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_84.setObjectName(_fromUtf8("label_84"))
        self.gridLayout_2.addWidget(self.label_84, 15, 1, 1, 1)
        self.label_85 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_85.setObjectName(_fromUtf8("label_85"))
        self.gridLayout_2.addWidget(self.label_85, 16, 1, 1, 1)
        self.label_86 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_86.setObjectName(_fromUtf8("label_86"))
        self.gridLayout_2.addWidget(self.label_86, 17, 1, 1, 1)
        self.label_87 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_87.setObjectName(_fromUtf8("label_87"))
        self.gridLayout_2.addWidget(self.label_87, 18, 1, 1, 1)
        self.label_88 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_88.setObjectName(_fromUtf8("label_88"))
        self.gridLayout_2.addWidget(self.label_88, 2, 2, 1, 1)
        self.label_89 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_89.setObjectName(_fromUtf8("label_89"))
        self.gridLayout_2.addWidget(self.label_89, 3, 2, 1, 1)
        self.label_90 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_90.setObjectName(_fromUtf8("label_90"))
        self.gridLayout_2.addWidget(self.label_90, 4, 2, 1, 1)
        self.label_91 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_91.setObjectName(_fromUtf8("label_91"))
        self.gridLayout_2.addWidget(self.label_91, 5, 2, 1, 1)
        self.label_92 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_92.setObjectName(_fromUtf8("label_92"))
        self.gridLayout_2.addWidget(self.label_92, 6, 2, 1, 1)
        self.label_93 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_93.setObjectName(_fromUtf8("label_93"))
        self.gridLayout_2.addWidget(self.label_93, 7, 2, 1, 1)
        self.label_94 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_94.setObjectName(_fromUtf8("label_94"))
        self.gridLayout_2.addWidget(self.label_94, 8, 2, 1, 1)
        self.label_95 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_95.setObjectName(_fromUtf8("label_95"))
        self.gridLayout_2.addWidget(self.label_95, 10, 2, 1, 1)
        self.label_96 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_96.setObjectName(_fromUtf8("label_96"))
        self.gridLayout_2.addWidget(self.label_96, 11, 2, 1, 1)
        self.label_97 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_97.setObjectName(_fromUtf8("label_97"))
        self.gridLayout_2.addWidget(self.label_97, 12, 2, 1, 1)
        self.label_98 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_98.setObjectName(_fromUtf8("label_98"))
        self.gridLayout_2.addWidget(self.label_98, 14, 2, 1, 1)
        self.label_99 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_99.setObjectName(_fromUtf8("label_99"))
        self.gridLayout_2.addWidget(self.label_99, 15, 2, 1, 1)
        self.label_100 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_100.setObjectName(_fromUtf8("label_100"))
        self.gridLayout_2.addWidget(self.label_100, 16, 2, 1, 1)
        self.label_101 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_101.setObjectName(_fromUtf8("label_101"))
        self.gridLayout_2.addWidget(self.label_101, 17, 2, 1, 1)
        self.label_102 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_102.setObjectName(_fromUtf8("label_102"))
        self.gridLayout_2.addWidget(self.label_102, 18, 2, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 690, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_39.setText(_translate("MainWindow", "26th,27th,28th", None))
        self.label_33.setText(_translate("MainWindow", "BasketBall Court", None))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Date</span></p></body></html>", None))
        self.label_71.setText(_translate("MainWindow", "26th,27th,28th", None))
        self.label_46.setText(_translate("MainWindow", "Lawn", None))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Events</span></p></body></html>", None))
        self.label_18.setText(_translate("MainWindow", "26th , 27th", None))
        self.label_76.setText(_translate("MainWindow", "FIFA 14", None))
        self.label_75.setText(_translate("MainWindow", "DOTA 2", None))
        self.label_26.setText(_translate("MainWindow", "Panna Football", None))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Date</span></p></body></html>", None))
        self.label_66.setText(_translate("MainWindow", "26th,27th", None))
        self.label_59.setText(_translate("MainWindow", "Be God", None))
        self.label_54.setText(_translate("MainWindow", "Crystal Maze", None))
        self.label_32.setText(_translate("MainWindow", "Foosball", None))
        self.label_56.setText(_translate("MainWindow", "Carrom(1v1) (2v2)", None))
        self.label_58.setText(_translate("MainWindow", "Chess", None))
        self.label_48.setText(_translate("MainWindow", "22nd,23th", None))
        self.label_51.setText(_translate("MainWindow", "Treasure Hunt", None))
        self.label_55.setText(_translate("MainWindow", "Drawing Hall", None))
        self.label_15.setText(_translate("MainWindow", "Robo Wars", None))
        self.label_69.setText(_translate("MainWindow", "ACID", None))
        self.label_42.setText(_translate("MainWindow", "Football", None))
        self.label_53.setText(_translate("MainWindow", "Phase 1 Lobby", None))
        self.label_30.setText(_translate("MainWindow", "Box Cricket", None))
        self.label_37.setText(_translate("MainWindow", "Rink Football", None))
        self.label_57.setText(_translate("MainWindow", "Room8/Room9/Room10", None))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">Special Attraction</span></p></body></html>", None))
        self.label_31.setText(_translate("MainWindow", "Cricket", None))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">Technical</span></p></body></html>", None))
        self.label_20.setText(_translate("MainWindow", "26th", None))
        self.label_47.setText(_translate("MainWindow", "Bowling", None))
        self.label_16.setText(_translate("MainWindow", "Poster Presentation", None))
        self.label_25.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">LAN</span></p></body></html>", None))
        self.label_11.setText(_translate("MainWindow", "Laser Tag", None))
        self.label_12.setText(_translate("MainWindow", "Coding", None))
        self.label_14.setText(_translate("MainWindow", "TTP", None))
        self.label_23.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">NEON</span></p></body></html>", None))
        self.label_73.setText(_translate("MainWindow", "CS 1.6 (5 V 5, 1 V1)", None))
        self.label_77.setText(_translate("MainWindow", "CS GO", None))
        self.label_78.setText(_translate("MainWindow", "NFS MW", None))
        self.label_13.setText(_translate("MainWindow", "Web Designing", None))
        self.label_24.setText(_translate("MainWindow", "BasketBall Court", None))
        self.label_44.setText(_translate("MainWindow", "Phase 3 Lobby", None))
        self.label_36.setText(_translate("MainWindow", "Selfie Contest", None))
        self.label_67.setText(_translate("MainWindow", "BasketBall Court", None))
        self.label_45.setText(_translate("MainWindow", "Lawn", None))
        self.label_64.setText(_translate("MainWindow", "Phase 1 Lobby", None))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">Mobile</span></p></body></html>", None))
        self.label_72.setText(_translate("MainWindow", "Campus", None))
        self.label_41.setText(_translate("MainWindow", "Zorb ball", None))
        self.label_22.setText(_translate("MainWindow", "27th", None))
        self.label_79.setText(_translate("MainWindow", "27th", None))
        self.label_19.setText(_translate("MainWindow", "27th", None))
        self.label_21.setText(_translate("MainWindow", "26th", None))
        self.label_43.setText(_translate("MainWindow", "BasketBall Court", None))
        self.label_3.setText(_translate("MainWindow", "COC/CR/ Mini Militia", None))
        self.label_34.setText(_translate("MainWindow", "26th,27th", None))
        self.label_62.setText(_translate("MainWindow", "26th, 27th", None))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Place</span></p></body></html>", None))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">Fun</span></p><p><br/></p></body></html>", None))
        self.label_52.setText(_translate("MainWindow", "26th, 27th,28th", None))
        self.label_7.setText(_translate("MainWindow", "Phase 1", None))
        self.label_65.setText(_translate("MainWindow", "26th,27th,28th", None))
        self.label_63.setText(_translate("MainWindow", "27th, 28th", None))
        self.label_70.setText(_translate("MainWindow", "Pokewalk", None))
        self.label_61.setText(_translate("MainWindow", "Drawing Hall", None))
        self.label_28.setText(_translate("MainWindow", "Hogathon", None))
        self.label_6.setText(_translate("MainWindow", "27th,28th", None))
        self.label_38.setText(_translate("MainWindow", "Paintball", None))
        self.label_29.setText(_translate("MainWindow", "27th , 28th", None))
        self.label_40.setText(_translate("MainWindow", "27,th 28th", None))
        self.label_35.setText(_translate("MainWindow", "Room 6", None))
        self.label_49.setText(_translate("MainWindow", "26th,27th,28th", None))
        self.label_74.setText(_translate("MainWindow", "26th,27th,28th", None))
        self.label_68.setText(_translate("MainWindow", "Shark Tank", None))
        self.label_80.setText(_translate("MainWindow", "26th , 27th", None))
        self.label_81.setText(_translate("MainWindow", "26th,27th", None))
        self.label_82.setText(_translate("MainWindow", "26th", None))
        self.label_83.setText(_translate("MainWindow", "26th , 27th", None))
        self.label_84.setText(_translate("MainWindow", "26th,27th", None))
        self.label_85.setText(_translate("MainWindow", "26th, 27th", None))
        self.label_86.setText(_translate("MainWindow", "26th, 27th", None))
        self.label_87.setText(_translate("MainWindow", "27th, 28th", None))
        self.label_88.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Place</span></p></body></html>", None))
        self.label_89.setText(_translate("MainWindow", "Room 7", None))
        self.label_90.setText(_translate("MainWindow", "Lenevo Lab (5th Floor)", None))
        self.label_91.setText(_translate("MainWindow", "TextLabel", None))
        self.label_92.setText(_translate("MainWindow", "Syndicate Room", None))
        self.label_93.setText(_translate("MainWindow", "Phase 3 Lobby", None))
        self.label_94.setText(_translate("MainWindow", "4Th Floor, PH", None))
        self.label_95.setText(_translate("MainWindow", "Room 13", None))
        self.label_96.setText(_translate("MainWindow", "Room 15", None))
        self.label_97.setText(_translate("MainWindow", "Room 14", None))
        self.label_98.setText(_translate("MainWindow", "Lab 3", None))
        self.label_99.setText(_translate("MainWindow", "Lab 4", None))
        self.label_100.setText(_translate("MainWindow", "Lab 2", None))
        self.label_101.setText(_translate("MainWindow", "Lab 1", None))
        self.label_102.setText(_translate("MainWindow", "Lab 4", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

